name: CI
on: [push]
jobs:
  build_go_1_24:
    name: go / 1.24 / build+test
    runs-on: ubuntu-latest
    steps:
    - name: setup go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
      id: go

    - name: checkout code
      uses: actions/checkout@v4

    - name: go get
      run: |
        go get -v ./...

    - name: go build
      run: go build -v gogctest.go

    - name: go test
      run: go test -race -v ./...

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        args: --max-issues-per-linter 500 --max-same-issues 500
